theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins


title: [Shamly's Github]
description: [Welcome to my site! Discover a little about me and my journey!]

# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

# github:
#   zip_url: http://example.com/download.zip
#   another_url: another value